name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List all files and paths
      run: |
        echo "Listing all files and paths in the repository:"
        find . -type f

    - name: Set Environment Variables
      run: |
        echo "PYTHONPATH=$PWD/login_testcases/homeobjects:$PWD/Config/configfile/config.py" >> $GITHUB_ENV
        echo "MONGO_URI=mongodb://127.0.0.1:27017/sampleupload" >> $GITHUB_ENV

    - name: Wait for MongoDB to be ready
      run: |
        until nc -zv localhost 27017; do
          echo "Waiting for MongoDB to start..."
          sleep 1
        done
        echo "MongoDB is ready"

    - name: Configure MongoDB Test Data
      run: |
        python configfile/config.py

    - name: Set up ChromeDriver and Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Set Timezone to India Standard Time (IST)
      run: sudo timedatectl set-timezone Asia/Kolkata

    - name: Run Selenium tests and generate HTML report
      id: run_tests
      run: |
        pytest --html=report.html --self-contained-html > pytest_test_results.log || true
        cat pytest_test_results.log

    - name: Check if tests passed or failed
      id: check_tests
      run: |
        if grep -q "FAILED" pytest_test_results.log; then
          echo "Tests failed"
          echo "TESTS_PASSED=false" >> $GITHUB_ENV
        else
          echo "Tests passed"
          echo "TESTS_PASSED=true" >> $GITHUB_ENV
        fi

    - name: Archive Pytest Results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: pytest_test_results.log

    - name: Archive HTML Test Report
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-report
        path: report.html

    - name: Validate Artifacts
      run: |
        if [ ! -f "pytest_test_results.log" ]; then
          echo "Failed to archive Pytest results"
          exit 1
        fi
        if [ ! -f "report.html" ]; then
          echo "Failed to archive HTML test report"
          exit 1
        fi
        echo "Artifacts validated successfully"

    - name: Send Failure Email Notification
      if: failure()
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: antony.silvesta@nidrive.in
      run: |
        echo "Tests failed! Sending failure email notification..."
        python send_email_notification.py "Tests failed on release push"

    - name: Send Success Email Notification
      if: success()
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: antony.silvesta@nidrive.in
      run: |
        echo "Tests passed! Sending success email notification..."
        python send_email_notification.py "Tests passed on release push"
